export { default as createTab } from './create'
export { default as allTabs } from './list'
export { default as getTab } from './get'
export { default as deleteTab } from './remove'
export { default as updateTab } from './edit'
