export { default as allCourses } from './list'
export { default as getCourse } from './get'
export { default as createCourse } from './create'
export { default as deleteCourse } from './remove'
export { default as updateCourse } from './edit'
